service: headless-html-resolver

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  memorySize: 1024
  timeout: 29
  logRetentionInDays: 3

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /html
          method: POST
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --no-warnings
